### ISSUE TITLE
[Idea]: suggest launch commands from a pre defined list?

### ISSUE THREAD

**Issue by zeltak** [thomp/dired-launch#10]
Hi, sorry for the multiple requests/ideas, i just really enjoy `dired-launch` *ALOT* and have various ideas related to the workflows :)

so related to #6 , maybe alongside suggesting which apps to launch based on file type , it could be great to also perhaps present (via helm,swiper etc) a list of predefined user commands to run.

for example i use filebot (a very cool media file renamer) quite often in dired via the `&` command. the command has several long switches such as

```
xterm -e filebot -script fn:amc --output "/home/zeltak/mounts/lraid/raid/ztmp/" --def @/home/zeltak/.config/filebot/Q.txt --action move --conflict skip -non-strict  --mode interactive *

#or

xterm -e filebot -script fn:amc --output "." --def @/home/zeltak/.config/filebot/here.txt --action move --conflict skip -non-strict --log-file ~/ZH_tmp/amc.log  --mode interactive *

```

instead of each time changing the parameters manually, one can perhaps define pre stored commands and then quick launch marked/single files with pre defined commands?

just a thought

thx

Z

**Comment by thomp** [comment]
This seems like a useful idea with two components -- (1) the issue of how and whether to present the executable options (helm/swiper/etc.) if multiple options exist and (2) the ability to specify more complex executable/argument combinations. With respect to the latter, are you envisioning something that allows you to simply specify, along with the executable, a complex, but _fixed_, set of arguments (i.e., irrespective of the file type/name/etc., you'd invoke filebot in the same manner)? Or something with programmatic flexibility (e.g., the ability, in `dired-launch-extensions-map`, to be able to specify a function which would accept file as an argument and _programmatically_ generate the executable and arguments -- e.g., allowing you to come up with a file- and directory-specific invocation of filebot)?

**Comment by zeltak** [comment]
Hi again!

yeah i do envision a way that along with the executable i can quick add a pre-defined complex and fixed set of arguments. 
As for presenting i would be personally fine with either helm or swiper i use and like both :)

I want to thank you again for all your hard work on this wonderful addition to dired (that for me super charges dired 10x :)) and would be happy to help in anyway needed (testing, documentation)

thx again

Z

**Comment by thomp** [comment]
With respect to the second point above, would you be willing to check out the branch at https://github.com/thomp/dired-launch/tree/custom-launch-commands ? It implements a relatively low-level approach to performing relatively arbitrary actions using a funcallable object. See `dired-launch-extensions-map` for an example for HTML files. I can also envision extending things by allowing for arbitrary specification of a combination of executable and arguments (e.g., simply allowing one to specify something like `("myexecutable" "arg1" "arg2" ... "argN"))`. The flexibility of the function approach seems attractive, but perhaps isn't as user-friendly. Maybe both approaches should be supported?

**Comment by thomp** [comment]
Opened new issue for first point... #11

**Comment by thomp** [comment]
See 788e8d4 and earlier commits

**Comment by zeltak** [comment]
Hi and thx for the late response...real life getting in the way

i cant really follow the html example. do i stick that inside my 

```
 (setq dired-launch-extensions-map
       '(
         ("mp4" ("mpv" "vlc"))
         ("mkv" ("mpv"))
         ("avi" ("mpv"))
         ("odt" ("libreofficedev5.3" "abiword"))
         ("png" ("phototonic"))
         ))

```

config?

Can you perhaps share some more examples? this sounds very exciting and i would love to test it out

thx so much again!

Z

**Comment by thomp** [comment]
1. Yes -- the `(list "html" ...)` example represents a potential member of `dired-launch-extensions-map`.
2. See https://github.com/thomp/dired-launch/wiki/Examples for a commented version of the 'html example'.
