### ISSUE TITLE
Please add a LICENSE

### ISSUE THREAD

**Issue by bandresen** [thomp/dired-launch#14]
This project is currently lacking a clearly stated free license.

Please consider adding one. :-)

Reference: https://github.com/emacsmirror/epkg-reports/blob/master/licenses-details.org

**Comment by thomp** [comment]
Thanks -- done. See https://github.com/thomp/dired-launch/commit/75745f2e40d060cae909f9e6f6ca2e5f725180b8

**Comment by thomp** [comment]
Thanks -- [done](75745f2e40d060cae909f9e6f6ca2e5f725180b8)
