### ISSUE TITLE
this is great! melpa version and predefined lists?

### ISSUE THREAD

**Issue by zeltak** [thomp/dired-launch#6]
Hi!

Thx so much for this package, been looking for something like this for ages :)

2 short questions:

1) will you submit this great addition to melpa

2) can i request also a third option: "Launch with predefined list by extension". that is define per file type X apps and when launched dired-launch will offer to open the file type with these pre defined apps based on the extension?

best

Z

**Comment by thomp** [comment]
1. It should be on MELPA -- see [MELPA's dired-launch page](https://melpa.org/#/dired-launch). If you're not able to access the package as a MELPA package, would you be willing to provide more detail regarding the problem?

**Comment by thomp** [comment]
A follow-up with your first question -- is the revised README.md (https://github.com/thomp/dired-launch/commit/e785dc6d274f4db52896765be4fdba03c9b12601) a bit more helpful with respect to MELPA and `dired-launch`?

**Comment by zeltak** [comment]
Hi!

ok i just managed to install from melpa with no issues. dont know what the issue was before

any thoughts on point #2?

**Comment by thomp** [comment]
I like the idea -- and can think of a few different ways one might implement your second request. Would you be willing to try out the [issue6 branch](https://github.com/thomp/dired-launch/blob/issue6/dired-launch.el)? It provides `dired-launch-extensions-map`, allowing you to specify one or more preferred applications corresponding to a given file extension. With the default keybindings, if the file type is present in  `dired-launch-extensions-map`, <key>J</key> should use the specified preferred application only when a single application is specified for a given file type (otherwise it will revert to using the generic launcher) while <key>K</key> should prompt, using the specified application(s) as completions.

**Comment by zeltak** [comment]
cool, im trying out the new branch now. i should mention before hand (spoilers.. ;-)) im very Un-technical and dont know how to code ;-)

so a few things :

1)how does one custom add other file types? it seems that M-x customize variable dosent have `dired-launch-extensions-map` option? can one define it with a `setq` in the init file?

2) when i launch it on a JPG using 'J' i get this error:

`apply: Searching for program: No such file or directory, mimeopen`

when i use 'K' i get first a "no match" error but then a selection with the predefined apps (gimp and phototonic) which is cool :)

unrelated but maybe a bug:
- it seems the keybinds ('J') are also held when using other dired modes such as 
https://github.com/juan-leon/dired-efap
other keybinds dont seem to have that behivour

Im very happy to help out in anyway i can (testing etc) ,thx for all your awesome work!!

Z

**Comment by thomp** [comment]
Separate issues the other items you noted: https://github.com/thomp/dired-launch/issues/7 and https://github.com/thomp/dired-launch/issues/8.

With respect to your first question, you can set `dired-launch-extensions-map` directly to whatever works for you -- `setq` in `~/.emacs` should be fine. Some examples:

     ;; define 'audacity' as the preferred application to open Ogg files
     (setq dired-launch-extensions-map
           '(("oga" ("audacity"))
             ("ogg" ("audacity"))))
	   
     ;; define 'vlc' as the preferred application for mp4 files, 'libreofficedev5.3' and 'abiword' as the preferred applications for odt (OpenDocument) files, and 'phototonic' as the preferred application for png files
     (setq dired-launch-extensions-map
           '(("mp4" ("vlc"))
             ("odt" ("libreofficedev5.3" "abiword"))
             ("png" ("phototonic"))))

**Comment by thomp** [comment]
See f8e6b5f
