### ISSUE TITLE
mimeopen on arch linux: still getting errors

### ISSUE THREAD

**Issue by zeltak** [thomp/dired-launch#9]
Hi again

so i have used this in my config

```
(setq dired-launch-default-launcher '("xdg-open"))
```

yet i still get this error when i issue `dired-launch-command`:

```
dired-launch-call-process-on: Searching for program: No such file or directory, mimeopenInvalid face reference: quote
```

any ideas why? using latest emacs and latest arch linux

best

Z

**Comment by thomp** [comment]
Thanks for taking the time to provide feedback. if you're using the [issue6](https://github.com/thomp/dired-launch/blob/issue6/dired-launch.el) branch, please load the [latest version](https://github.com/thomp/dired-launch/blob/master/dired-launch.el) of `dired-launch` (a 'quick-and-dirty' way is to click 'Raw', download the raw file, <kbd>M-x</kbd> `ielm`, and then load that file with `(load "/path/to/the/current/dired-launch.el")`).

Try launching with <kbd>J</kbd> again. Does the above error still occur? If you encounter a different error, what is it? If you encounter the same (or similar) error, move to ielm (<kbd>M-x</kbd> ielm) and verify that the value of `dired-launch-default-launcher` is what you think it is:

    ELISP> dired-launch-default-launcher
    ("xdg-open")

**Comment by zeltak** [comment]
Hi and thx for the quick reply!

so this time there is no error but nothing launches using `dired-launch-command`

i did verify the 

```
ELISP> dired-launch-default-launcher
("xdg-open")
```

and have tried it on a mp4 file with this in my config

```
ELISP> dired-launch-extensions-map

(("mp4"
  ("mpv"))
 ("mkv"
  ("mpv"))
 ("avi"
  ("mpv"))
 ("odt"
  ("libreofficedev5.3" "abiword"))
 ("png"
  ("phototonic")))
```

anything else i should try?

z

**Comment by thomp** [comment]
This should be fixed with 82d8e08. Would you be willing to test out the [latest version](https://github.com/thomp/dired-launch/blob/master/dired-launch.el) and see if it works with files that have xdg-open associations?

By the way, when you use current `dired-launch` (not the `issue6` branch), `dired-launch-extensions-map` is irrelevant (I haven't merged that functionality into the master yet). Once it's clear the default launcher is functioning, I'll try and merge that goodness in...

**Comment by zeltak** [comment]
Awesome, i can confirm that with https://github.com/thomp/dired-launch/commit/82d8e08bfe7c68e4f2f3442f50ba72bf7eb393be id does work! :)

im willing to help out testing the new `dired-launch-extensions-map` functionality or really anything else that needs testing :)

best

Z

**Comment by thomp** [comment]
Great!
